notifications:
  email: false

language: python

sudo: false

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

env:
  global:
    - CFLAGS="-O0"
  matrix:
    - TOXENV=flake8
    - TOXENV=py27-1.11
    - TOXENV=py36-1.11

install:
  - pip install tox codecov
  - sed -r
    -e "s,(MAPIT_DB_USER:) 'mapit',\\1 'postgres',"
    conf/general.yml-example > conf/general.yml

before_script:
  - createdb -U postgres mapit
  - psql -U postgres -d mapit -c 'CREATE EXTENSION postgis;'

script:
  - tox

after_success:
  - codecov
